# データセット
https://www.kaggle.com/CooperUnion/anime-recommendations-database

In [104]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [105]:
os.listdir("./input/")

['anime.csv', 'rating.csv']

In [106]:
anime = pd.read_csv("./input/anime.csv")

In [107]:
user = pd.read_csv("./input/rating.csv")

# anime

In [108]:
anime

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266
...,...,...,...,...,...,...,...
12289,9316,Toushindai My Lover: Minami tai Mecha-Minami,Hentai,OVA,1,4.15,211
12290,5543,Under World,Hentai,OVA,1,4.28,183
12291,5621,Violence Gekiga David no Hoshi,Hentai,OVA,4,4.88,219
12292,6133,Violence Gekiga Shin David no Hoshi: Inma Dens...,Hentai,OVA,1,4.98,175
12293,26081,Yasuji no Pornorama: Yacchimae!!,Hentai,Movie,1,5.46,142

# rating
ratingは、10段階の評価値になっている。  
-1は、見たけど評価していない

In [109]:
#rating['rating'].name = "user_rating"
user.rename(columns={'rating': 'user_rating'}, inplace=True)

In [110]:
#min
max_user_rating = user.groupby("user_id")["user_rating"].max().reset_index()
max_user_rating.rename(columns={"user_rating": "max_user_rating"}, inplace=True)

#max
min_user_rating = user.groupby("user_id")["user_rating"].min().reset_index()
min_user_rating.rename(columns={"user_rating": "min_user_rating"}, inplace=True)

#mean
mean_user_rating = user.groupby("user_id")["user_rating"].mean().reset_index()
mean_user_rating.rename(columns={"user_rating": "mean_user_rating"}, inplace=True)

#median
median_user_rating = user.groupby("user_id")["user_rating"].median().reset_index()
median_user_rating.rename(columns={"user_rating": "median_user_rating"}, inplace=True)

#std
std_user_rating = user.groupby("user_id")["user_rating"].std().reset_index()
std_user_rating.rename(columns={"user_rating": "std_user_rating"}, inplace=True)

In [111]:
user = pd.merge(user, min_user_rating, on="user_id", how="left")
user = pd.merge(user, max_user_rating, on="user_id", how="left")
user = pd.merge(user, mean_user_rating, on="user_id", how="left")
user = pd.merge(user, median_user_rating, on="user_id", how="left")
user = pd.merge(user, std_user_rating, on="user_id", how="left")

In [114]:
user["relative_user_rating"] = (user["user_rating"]-user["min_user_rating"])/(user["max_user_rating"]-user["min_user_rating"])
user["relative_user_rating"].fillna(0.5, inplace=True)

In [115]:
user

,user_id,anime_id,user_rating,min_user_rating,max_user_rating,mean_user_rating,median_user_rating,std_user_rating,relative_user_rating
0,1,20,-1,-1,10,-0.712418,-1.0,1.760955,0.000000
1,1,24,-1,-1,10,-0.712418,-1.0,1.760955,0.000000
2,1,79,-1,-1,10,-0.712418,-1.0,1.760955,0.000000
3,1,226,-1,-1,10,-0.712418,-1.0,1.760955,0.000000
4,1,241,-1,-1,10,-0.712418,-1.0,1.760955,0.000000
...,...,...,...,...,...,...,...,...,...
7813732,73515,16512,7,-1,10,7.719388,9.0,2.904962,0.727273
7813733,73515,17187,9,-1,10,7.719388,9.0,2.904962,0.909091
7813734,73515,22145,10,-1,10,7.719388,9.0,2.904962,1.000000
7813735,73516,790,9,9,9,9.000000,9.0,0.000000,0.500000
7813736,73516,8074,9,9,9,9.000000,9.0,0.000000,0.500000

# df

In [57]:
df = pd.merge(user, anime, on="anime_id", how="left")

In [58]:
df

,user_id,anime_id,user_rating,name,genre,type,episodes,rating,members
0,1,20,-1,Naruto,"Action, Comedy, Martial Arts, Shounen, Super P...",TV,220,7.81,683297.0
1,1,24,-1,School Rumble,"Comedy, Romance, School, Shounen",TV,26,8.06,178553.0
2,1,79,-1,Shuffle!,"Comedy, Drama, Ecchi, Fantasy, Harem, Magic, R...",TV,24,7.31,158772.0
3,1,226,-1,Elfen Lied,"Action, Drama, Horror, Psychological, Romance,...",TV,13,7.85,623511.0
4,1,241,-1,Girls Bravo: First Season,"Comedy, Ecchi, Fantasy, Harem, Romance, School",TV,11,6.69,84395.0
...,...,...,...,...,...,...,...,...,...
7813732,73515,16512,7,Devil Survivor 2 The Animation,"Action, Demons, Supernatural",TV,13,7.06,101266.0
7813733,73515,17187,9,Ghost in the Shell: Arise - Border:1 Ghost Pain,"Mecha, Police, Psychological, Sci-Fi",Movie,1,7.64,31747.0
7813734,73515,22145,10,Kuroshitsuji: Book of Circus,"Comedy, Demons, Fantasy, Historical, Shounen, ...",TV,10,8.37,122895.0
7813735,73516,790,9,Ergo Proxy,"Mystery, Psychological, Sci-Fi",TV,23,8.03,265005.0
7813736,73516,8074,9,Highschool of the Dead,"Action, Ecchi, Horror, Supernatural",TV,12,7.46,535892.0

In [65]:
select = [i+1 for i in range(20)]
df_1_20 = df[df["user_id"].isin(select)]
df_1_20

,user_id,anime_id,user_rating,name,genre,type,episodes,rating,members
0,1,20,-1,Naruto,"Action, Comedy, Martial Arts, Shounen, Super P...",TV,220,7.81,683297.0
1,1,24,-1,School Rumble,"Comedy, Romance, School, Shounen",TV,26,8.06,178553.0
2,1,79,-1,Shuffle!,"Comedy, Drama, Ecchi, Fantasy, Harem, Magic, R...",TV,24,7.31,158772.0
3,1,226,-1,Elfen Lied,"Action, Drama, Horror, Psychological, Romance,...",TV,13,7.85,623511.0
4,1,241,-1,Girls Bravo: First Season,"Comedy, Ecchi, Fantasy, Harem, Romance, School",TV,11,6.69,84395.0
...,...,...,...,...,...,...,...,...,...
2275,20,8876,10,Koe de Oshigoto! The Animation,"Comedy, Ecchi, Seinen",OVA,2,7.13,57466.0
2276,20,10073,10,Seikon no Qwaser II,"Action, Ecchi, Seinen, Super Power, Supernatural",TV,12,6.69,64168.0
2277,20,10076,10,Kämpfer für die Liebe,"Action, Comedy, Ecchi, Shoujo Ai, Super Power",Special,2,6.69,37047.0
2278,20,10620,10,Mirai Nikki (TV),"Action, Mystery, Psychological, Shounen, Super...",TV,26,8.07,657190.0
2279,20,12581,10,Asa made Jugyou Chu!,"Comedy, Ecchi, Romance, School",OVA,1,6.37,25285.0